version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: dailynotes-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db

  server:
    build:
      context: ./server
    container_name: dailynotes-server
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
    container_name: dailynotes-client
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    depends_on:
      - server

volumes:
  mongodb-data:
